name: CI-CD front

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix: 
        node-version: [20.3.1] 

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }} 
      
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/front .
          docker push ${{ secrets.DOCKER_REPO }}/front

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Copy docker-compose.yml to EC2
        run: |
          scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ./docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
      

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Listing all Docker containers:"
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ubuntu:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/front
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f
          EOF
